### ISSUE TITLE
Error reading wad file

### ISSUE THREAD

**Issue by RealRexen** [Spectere/Wadinator#10]
Got this error on windows 11 when it pick the wad 
![image](https://github.com/Spectere/Wadinator/assets/18408903/fe102a99-3983-48b1-a019-72bf2cc03469)

wad: 
[mapsofchaos-hc.zip](https://github.com/Spectere/Wadinator/files/11820973/mapsofchaos-hc.zip)
Zip file is just a renamed wad so I can upload it.

This was done in windows terminal and using v1.4.0 of Wadinator. Wadinator is located in C:\Users\rexth\Desktop\Wadinator

**Comment by Spectere** [comment]
Hey Rexen! Thanks for the report.

Looks like the issue stems from some improper map name filtering (whoopsie!), coupled with the fact that MoC contains both Doom and Doom II maps. I just pushed out a fix for that. Updated binaries will be available in a few minutes. :)
